### ISSUE TITLE
Assume that the distributed transaction Cancel method fails

### ISSUE THREAD

**Issue by benxionghu** [liuhll/silky#15]
In a distributed framework, if my cancel method fails, it will retry several times. Can I set the number of retries myself

**Comment by liuhll** [comment]
This is a good idea, but such settings are not currently supported, and such configuration items will be considered later.

**Comment by liuhll** [comment]
The best way to use distributed transactions is not to throw exceptions during the Comfirming or Canceling phase

**Comment by 1301536601** [comment]
> In a distributed framework, if my cancel method fails, it will retry several times. Can I set the number of retries myself



> 使用分布式事务的最佳方式是在确认或取消阶段不要抛出异常



> The best way to use distributed transactions is not to throw exceptions during the Comfirming or Canceling phase

**Comment by benxionghu** [comment]
> The best way to use distributed transactions is not to throw exceptions during the Comfirming or Canceling phase

I can understand what you mean, but there are database or interface operations when canceling the operation, since it is related to the network, there will be a possibility of failure.  That's why the question comes up
