### ISSUE TITLE
有集成消息队列的计划吗？例如rabbitmq？

### ISSUE THREAD

**Issue by feelhum** [liuhll/silky#17]
有集成消息队列的计划吗？例如rabbitmq？

**Comment by liuhll** [comment]
暂时没有,silky的可扩展性非常强的,您可以很方便的与第三方的分布式消息组件集成.例如:[CAP](https://github.com/dotnetcore/CAP) 或是[MassTransit](https://github.com/MassTransit/MassTransit).
你只需要继承:`IConfigureService`接口或是在自定义模块中提供的方法`ConfigureServices(IServiceCollection services, IConfiguration configuration)`,使用`services`引入第三方组件的服务就可以与第三方组件集成。

**Comment by feelhum** [comment]
感谢回复，,silky是非常不错的微服务框架。我尝试集成。

**Comment by zhuzhao** [comment]
不错
