### ISSUE TITLE
当前模板生成的项目报错

### ISSUE THREAD

**Issue by dbabox** [liuhll/silky#28]
Silky.App.Template::3.2.0

提示未包含  UseSilkyHttpServer 的定义
app.UseSilkyHttpServer();

**Comment by liuhll** [comment]
这个中间件的名称被我重命名为`app.UseSilkyWebServer()`；你修改为`app.UseSilkyWebServer()` 发布的时候忘记修改模板了！下个版本会修复的。

**Comment by liuhll** [comment]
[2020年度总结(刘洪亮).docx](https://github.com/liuhll/silky/files/8795319/2020.docx)
